const mockActivities = [
  {
    id: 1,
    activity: 'canceled',
    timestamp: new Date().getTime(),
    token: 'binance',
    value: 0,
    streamTo: 'crypto-master',
    streamForm: '',
    rate: '',
  },
  {
    id: 2,
    activity: 'withdrew',
    timestamp: new Date().getTime(),
    token: 'ether',
    value: 1.8,
    streamTo: 'ether-miner',
    streamForm: '',
    rate: '',
  },
  {
    id: 3,
    activity: 'streaming',
    timestamp: new Date().getTime(),
    token: 'ether',
    value: 1.5,
    streamTo: 'ether-miner',
    streamForm: '',
    rate: 'per day',
  },
  {
    id: 4,
    activity: 'streaming',
    timestamp: new Date().getTime(),
    token: 'bitcoin',
    value: 1.75,
    streamTo: '',
    streamForm: 'coineeze',
    rate: 'per hour',
  },
  {
    id: 5,
    activity: 'deposited',
    timestamp: new Date().getTime(),
    token: 'ripple',
    value: 25.75,
    streamTo: '',
    streamForm: '',
    rate: '',
  },
];

export default mockActivities;
